// Generated by Cursor
// Alpha 24-02-26 routes – single-search-results and combined-search-results journeys

const BASE = '/alpha-24-02-26'

module.exports = (router) => {
  // Single search results – search-results (form posts to itself)
  router.get(`${BASE}/single-search-results/search-results`, (req, res) => {
    res.render('alpha-24-02-26/single-search-results/search-results')
  })

  router.post(`${BASE}/single-search-results/search-results`, (req, res) => {
    const data = req.session.data || {}
    const permitReferences = (req.body.permitReferences || '').trim()

    delete data.errors
    delete data.errorList

    if (!permitReferences) {
      data.errors = { permitReferences: 'Enter at least one permit reference' }
      data.errorList = [
        { text: 'Enter at least one permit reference', href: '#permitReferences' }
      ]
      return res.redirect(`${BASE}/single-search-results/search-results`)
    }

    data.permitReferences = permitReferences
    delete data.errors
    delete data.errorList
    res.redirect(`${BASE}/single-search-results/permit-search-results`)
  })

  router.get(`${BASE}/single-search-results/permit-search-results`, (req, res) => {
    res.render('alpha-24-02-26/single-search-results/permit-search-results')
  })

  router.get(`${BASE}/single-search-results/check-permit-details`, (req, res) => {
    const data = req.session.data || {}
    data.permit = req.query.permit || data.permit
    if (req.query.edit === '1') {
      data.endorsed = false
      data.refused = false
    } else {
      data.endorsed = req.query.endorsed === '1' || data.endorsed
      data.refused = req.query.refused === '1' || data.refused
    }
    res.render('alpha-24-02-26/single-search-results/check-permit-details')
  })

  router.post(`${BASE}/single-search-results/check-permit-details`, (req, res) => {
    const data = req.session.data || {}
    data.permit = req.body.permit || req.query.permit || data.permit

    const actualQuantity = (req.body.actualQuantity || '').trim()
    const deadOnArrival = (req.body.deadOnArrival || '').trim()
    const mrnReference = (req.body.mrnReference || '').trim()
    const awbReference = (req.body.awbReference || '').trim()

    const isEndorse = !!req.body.endorse
    const isRefuse = !!req.body.refuse

    delete data.errors
    delete data.errorList
    data.actualQuantity = actualQuantity
    data.deadOnArrival = deadOnArrival
    data.mrnReference = mrnReference
    data.awbReference = awbReference

    const errors = {}
    const errorList = []

    if (isEndorse) {
      if (!actualQuantity) {
        errors.actualQuantity = 'Enter the actual quantity'
        errorList.push({ text: 'Enter the actual quantity', href: '#actualQuantity' })
      } else if (!/^\d+$/.test(actualQuantity) || parseInt(actualQuantity, 10) < 1) {
        errors.actualQuantity = 'Actual quantity must be a whole number of 1 or more'
        errorList.push({ text: 'Actual quantity must be a whole number of 1 or more', href: '#actualQuantity' })
      }

      if (!deadOnArrival) {
        errors.deadOnArrival = 'Enter the number of animals dead on arrival'
        errorList.push({ text: 'Enter the number of animals dead on arrival', href: '#deadOnArrival' })
      } else if (!/^\d+$/.test(deadOnArrival) || parseInt(deadOnArrival, 10) < 0) {
        errors.deadOnArrival = 'Number must be 0 or more'
        errorList.push({ text: 'Number must be 0 or more', href: '#deadOnArrival' })
      }

      if (!mrnReference) {
        errors.mrnReference = 'Enter the CDS MRN reference'
        errorList.push({ text: 'Enter the CDS MRN reference', href: '#mrnReference' })
      }

      if (!awbReference) {
        errors.awbReference = 'Enter the Bill of Lading or Air waybill (AWB) reference'
        errorList.push({ text: 'Enter the Bill of Lading or Air waybill (AWB) reference', href: '#awbReference' })
      }
    }

    if (errorList.length > 0) {
      data.errors = errors
      data.errorList = errorList
      return res.redirect(`${BASE}/single-search-results/check-permit-details?permit=${encodeURIComponent(data.permit || '')}`)
    }

    delete data.errors
    delete data.errorList
    const permitId = data.permit || '26GBIMP12344X'
    data.permitStatuses = data.permitStatuses || {}
    if (isEndorse) {
      data.endorsed = true
      data.refused = false
      data.permitStatuses[permitId] = 'endorsed'
      res.redirect(`${BASE}/single-search-results/check-permit-details?permit=${encodeURIComponent(permitId)}&endorsed=1`)
    } else {
      data.refused = true
      data.endorsed = false
      data.permitStatuses[permitId] = 'refused'
      res.redirect(`${BASE}/single-search-results/check-permit-details?permit=${encodeURIComponent(permitId)}&refused=1`)
    }
  })

  // Add more routes here as you add pages
}
