// Generated by Cursor
// Alpha 02-03-26 routes – single search results journey only

const BASE = '/alpha-02-03-26'

module.exports = (router) => {
  const DEFAULT_PERMIT_REFS = [
    '25GBIMPABS719', '25GBIMPSTYXH1', '25GBIMPSTYHNO', '25GBIMPUVWOFM', '25GBIMPWX0N12',
    '25GBIMPYZOPGY', '25GBIMPABZPMT', '25GBIMPCDO2DA', '25GBIMPEFPJOB', '25GBIMPGHAQTG'
  ]

  function buildAndSortPermitList (refs, permitData) {
    const items = refs.map(ref => {
      const item = permitData[ref] || { species: '–', commonName: '–', description: '–', expires: '–', quantity: '–' }
      return { ref, ...item }
    })
    items.sort((a, b) => {
      if (a.expires === '–') return 1
      if (b.expires === '–') return -1
      const dateDiff = new Date(a.expires) - new Date(b.expires)
      if (dateDiff !== 0) return dateDiff
      return (a.ref || '').localeCompare(b.ref || '')
    })
    return items
  }

  router.get(`${BASE}/single-search-results/search-results`, (req, res) => {
    const data = req.session.data || {}
    if (req.query.prefill === '1') {
      data.permitReferences = DEFAULT_PERMIT_REFS.join('\n')
    }
    res.render('alpha-02-03-26/single-search-results/search-results')
  })

  const PERMIT_SEARCH_DATA = {
    '25GBIMPABS719': { species: 'Alligator mississippiensis', commonName: 'American alligator', description: 'Watch straps made of Alligator skin', expires: '9 March 2026', quantity: '20' },
    '25GBIMPSTYXH1': { species: 'Alligator mississippiensis', commonName: 'American alligator', description: 'Watch straps made of Alligator skin', expires: '9 March 2026', quantity: '100' },
    '25GBIMPSTYHNO': { species: 'Alligator mississippiensis', commonName: 'American alligator', description: 'Watch straps made of Alligator skin', expires: '10 March 2026', quantity: '80' },
    '25GBIMPUVWOFM': { species: 'Alligator mississippiensis', commonName: 'American alligator', description: 'Watch straps made of Alligator skin', expires: '10 March 2026', quantity: '80' },
    '25GBIMPWX0N12': { species: 'Alligator mississippiensis', commonName: 'American alligator', description: 'Watch straps made of Alligator skin', expires: '10 March 2026', quantity: '80' },
    '25GBIMPYZOPGY': { species: 'Alligator mississippiensis', commonName: 'American alligator', description: 'Watch straps made of Alligator skin', expires: '11 March 2026', quantity: '20' },
    '25GBIMPABZPMT': { species: 'Alligator mississippiensis', commonName: 'American alligator', description: 'Watch straps made of Alligator skin', expires: '11 March 2026', quantity: '20' },
    '25GBIMPCDO2DA': { species: 'Alligator mississippiensis', commonName: 'American alligator', description: 'Watch straps made of Alligator skin', expires: '11 March 2026', quantity: '50' },
    '25GBIMPEFPJOB': { species: 'Alligator mississippiensis', commonName: 'American alligator', description: 'Watch straps made of Alligator skin', expires: '9 March 2026', quantity: '30' },
    '25GBIMPGHAQTG': { species: 'Alligator mississippiensis', commonName: 'American alligator', description: 'Watch straps made of Alligator skin', expires: '11 March 2026', quantity: '10' },
    '26GBIMP12344X': { species: 'Alligator mississippiensis', commonName: 'American alligator', description: 'Watch straps made of Alligator skin', expires: '9 March 2026', quantity: '20' },
    '26GBIMP7GH45R': { species: 'Alligator mississippiensis', commonName: 'American alligator', description: 'Watch straps made of Alligator skin', expires: '9 March 2026', quantity: '100' },
    '26GBIMPHG453Y': { species: 'Alligator mississippiensis', commonName: 'American alligator', description: 'Watch straps made of Alligator skin', expires: '10 March 2026', quantity: '80' },
    '26GBIMP4AB123': { species: 'Alligator mississippiensis', commonName: 'American alligator', description: 'Watch straps made of Alligator skin', expires: '10 March 2026', quantity: '80' },
    '26GBIMP5CD456': { species: 'Alligator mississippiensis', commonName: 'American alligator', description: 'Watch straps made of Alligator skin', expires: '10 March 2026', quantity: '80' },
    '26GBIMP6EF789': { species: 'Alligator mississippiensis', commonName: 'American alligator', description: 'Watch straps made of Alligator skin', expires: '11 March 2026', quantity: '20' },
    '26GBIMP7GH012': { species: 'Alligator mississippiensis', commonName: 'American alligator', description: 'Watch straps made of Alligator skin', expires: '11 March 2026', quantity: '20' },
    '26GBIMP8IJ345': { species: 'Alligator mississippiensis', commonName: 'American alligator', description: 'Watch straps made of Alligator skin', expires: '11 March 2026', quantity: '50' },
    '26GBIMP9KL678': { species: 'Alligator mississippiensis', commonName: 'American alligator', description: 'Watch straps made of Alligator skin', expires: '9 March 2026', quantity: '30' },
    '26GBIMP0MN901': { species: 'Alligator mississippiensis', commonName: 'American alligator', description: 'Watch straps made of Alligator skin', expires: '11 March 2026', quantity: '10' }
  }

  router.post(`${BASE}/single-search-results/search-results`, (req, res) => {
    const data = req.session.data || {}
    const permitReferences = (req.body.permitReferences || '').trim()

    delete data.errors
    delete data.errorList

    if (!permitReferences) {
      data.errors = { permitReferences: 'Enter at least one permit reference' }
      data.errorList = [
        { text: 'Enter at least one permit reference', href: '#permitReferences' }
      ]
      return res.redirect(`${BASE}/single-search-results/search-results`)
    }

    const refs = permitReferences
      .split(/[\n,]+/)
      .map(r => r.trim())
      .filter(r => r)

    data.permitReferences = permitReferences
    data.searchedPermits = refs
    delete data.errors
    delete data.errorList
    req.session.save((err) => {
      if (err) return res.redirect(`${BASE}/single-search-results/search-results`)
      res.redirect(`${BASE}/single-search-results/permit-search-results`)
    })
  })

  router.get(`${BASE}/single-search-results/permit-search-results`, (req, res) => {
    res.set('Cache-Control', 'no-store, no-cache, must-revalidate, private')
    res.set('Pragma', 'no-cache')
    res.set('Expires', '0')
    const data = req.session.data || {}
    let refs = data.searchedPermits || DEFAULT_PERMIT_REFS
    if (refs.length === 0) refs = DEFAULT_PERMIT_REFS
    const permitStatuses = data.permitStatuses || {}
    const items = buildAndSortPermitList(refs, PERMIT_SEARCH_DATA)
    data.permitSearchResults = items
    data.permitSearchRows = items.map((item, idx) => {
      const status = permitStatuses[item.ref]
      let tag = '<strong class="govuk-tag govuk-tag--blue">Valid</strong>'
      if (status === 'endorsed') tag = '<strong class="govuk-tag govuk-tag--green">Endorsed</strong>'
      else if (status === 'refused') tag = '<strong class="govuk-tag govuk-tag--red">Refused</strong>'
      const pageNum = Math.min(idx + 1, 10)
      const checkHref = `${BASE}/single-search-results/check-permit-${pageNum}`
      return [
        { text: item.ref },
        { text: item.species },
        { text: item.quantity },
        { text: item.expires },
        { html: tag },
        { html: `<a href="${checkHref}">Check permit</a>` }
      ]
    })
    res.locals.data.permitSearchResults = data.permitSearchResults
    res.locals.data.permitSearchRows = data.permitSearchRows
    res.render('alpha-02-03-26/single-search-results/permit-search-results')
  })

  const STATIC_PERMIT_PAGES = [
    'check-permit-1', 'check-permit-2', 'check-permit-3', 'check-permit-4', 'check-permit-5',
    'check-permit-6', 'check-permit-7', 'check-permit-8', 'check-permit-9', 'check-permit-10'
  ]
  STATIC_PERMIT_PAGES.forEach((page) => {
    router.get(`${BASE}/single-search-results/${page}`, (req, res) => {
      res.render(`alpha-02-03-26/single-search-results/${page}`)
    })
  })

  router.get(`${BASE}/single-search-results/refuse-permit`, (req, res) => {
    const data = req.session.data || {}
    let refs = data.searchedPermits || DEFAULT_PERMIT_REFS
    if (refs.length === 0) refs = DEFAULT_PERMIT_REFS
    const permitList = buildAndSortPermitList(refs, PERMIT_SEARCH_DATA)
    const permitRef = (req.query.permit || '').trim() || data.permit || '25GBIMPABS719'
    let currentIndex = permitList.findIndex(p => p.ref === permitRef) + 1
    if (currentIndex < 1) currentIndex = 1
    if (currentIndex > permitList.length) currentIndex = permitList.length
    const currentPermit = permitList[currentIndex - 1] || {}
    data.permit = currentPermit.ref
    data.currentPermit = currentPermit
    res.locals.data.permit = currentPermit.ref
    res.locals.data.currentPermit = currentPermit
    res.render('alpha-02-03-26/single-search-results/refuse-permit')
  })

  router.post(`${BASE}/single-search-results/refuse-permit`, (req, res) => {
    const data = req.session.data || {}
    const permitId = (req.body.permit || '').trim() || data.permit || '25GBIMPABS719'
    const refusalReason = (req.body.refusalReason || '').trim()
    const additionalDetails = (req.body.additionalDetails || req.body.additionalDetailsAlt || '').trim().slice(0, 200)

    delete data.errors
    delete data.errorList

    const errors = {}
    const errorList = []

    if (!refusalReason) {
      errors.refusalReason = 'Select a reason for refusing this permit'
      errorList.push({ text: 'Select a reason for refusing this permit', href: '#refusalReason' })
    }

    if (errorList.length > 0) {
      data.errors = errors
      data.errorList = errorList
      data.additionalDetails = req.body.additionalDetails || req.body.additionalDetailsAlt || ''
      return res.redirect(`${BASE}/single-search-results/refuse-permit?permit=${encodeURIComponent(permitId)}`)
    }

    const permitList = buildAndSortPermitList(data.searchedPermits || DEFAULT_PERMIT_REFS, PERMIT_SEARCH_DATA)
    const currentPermit = permitList.find(p => p.ref === permitId) || {}
    const port = currentPermit.port || 'Dover'
    const officerId = '233215'

    const now = new Date()
    const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
    const day = now.getDate()
    const month = months[now.getMonth()]
    const year = now.getFullYear()
    const hours = String(now.getHours()).padStart(2, '0')
    const minutes = String(now.getMinutes()).padStart(2, '0')
    const dateOfRefusal = `${day} ${month} ${year}, ${hours}:${minutes}`

    data.endorsedDetails = data.endorsedDetails || {}
    data.endorsedDetails[permitId] = {
      refusalReason,
      additionalDetails: additionalDetails || null,
      dateOfRefusal,
      port,
      officerId
    }
    data.permitStatuses = data.permitStatuses || {}
    data.permitStatuses[permitId] = 'refused'
    data.endorsed = false
    data.refused = true
    data.successPermit = permitId
    res.redirect(`${BASE}/single-search-results/check-permit-details?permit=${encodeURIComponent(permitId)}&refused=1`)
  })

  router.get(`${BASE}/single-search-results/check-permit-details`, (req, res) => {
    const data = req.session.data || {}
    let refs = data.searchedPermits || DEFAULT_PERMIT_REFS
    if (refs.length === 0) refs = DEFAULT_PERMIT_REFS
    const permitList = buildAndSortPermitList(refs, PERMIT_SEARCH_DATA)
    data.permitSearchResults = permitList
    const totalCount = permitList.length
    const permitRef = (req.query.permit || '').trim()
    let currentIndex = permitList.findIndex(p => p.ref === permitRef) + 1
    if (currentIndex < 1) currentIndex = 1
    if (currentIndex > totalCount) currentIndex = totalCount
    const currentPermit = permitList[currentIndex - 1]
    data.permit = currentPermit.ref
    data.currentPermit = currentPermit
    data.checkPermitIndex = currentIndex
    data.checkPermitTotal = totalCount
    data.checkPermitList = permitList
    res.locals.data.checkPermitList = permitList
    res.locals.data.checkPermitIndex = currentIndex
    res.locals.data.checkPermitTotal = totalCount
    res.locals.data.permit = currentPermit.ref
    res.locals.data.currentPermit = currentPermit
    if (req.query.applyReference === '1' && req.query.mrnReference) {
      data.mrnReference = (req.query.mrnReference || '').trim()
      return res.redirect(`${BASE}/single-search-results/check-permit-details?permit=${encodeURIComponent(permitRef || data.permit)}`)
    }
    if (req.query.edit === '1') {
      delete data.endorsed
      delete data.refused
      delete data.updated
      delete data.successPermit
      data.editEndorsement = true
      res.locals.data.editEndorsement = true
    } else {
      data.editEndorsement = false
      res.locals.data.editEndorsement = false
      if (req.query.endorsed === '1') {
        data.endorsed = true
        data.successPermit = permitRef
        delete data.refused
        delete data.updated
      } else if (req.query.refused === '1') {
        data.refused = true
        data.successPermit = permitRef
        delete data.endorsed
        delete data.updated
      } else if (req.query.updated === '1') {
        data.updated = true
        data.successPermit = permitRef
        res.locals.data.updated = true
        delete data.endorsed
        delete data.refused
      } else {
        delete data.endorsed
        delete data.refused
        delete data.updated
      }
      if (data.successPermit && data.successPermit !== permitRef) {
        delete data.endorsed
        delete data.refused
        delete data.updated
        delete data.successPermit
      }
    }
    // Override in res.locals – autoStoreData populates res.locals.data before our route runs,
    // so we must update locals for the template to see editEndorsement and banner flags
    if (req.query.endorsed !== '1') delete res.locals.data.endorsed
    if (req.query.refused !== '1') delete res.locals.data.refused
    if (req.query.updated === '1') res.locals.data.updated = true
    else delete res.locals.data.updated
    if (res.locals.data.successPermit && res.locals.data.successPermit !== permitRef) {
      delete res.locals.data.endorsed
      delete res.locals.data.refused
      delete res.locals.data.updated
      delete res.locals.data.successPermit
    }
    res.render('alpha-02-03-26/single-search-results/check-permit-details')
  })

  router.post(`${BASE}/single-search-results/check-permit-details`, (req, res) => {
    const data = req.session.data || {}
    const permitId = (req.body.permit || '').trim() || data.permit || '25GBIMPABS719'
    let refs = data.searchedPermits || DEFAULT_PERMIT_REFS
    if (refs.length === 0) refs = DEFAULT_PERMIT_REFS
    const permitList = buildAndSortPermitList(refs, PERMIT_SEARCH_DATA)
    const totalCount = permitList.length || 10
    let currentIndex = permitList.findIndex(p => p.ref === permitId) + 1
    if (currentIndex < 1) currentIndex = 1
    const currentPermit = permitList[currentIndex - 1] || {}

    const actualQuantity = (req.body.actualQuantity || '').trim()
    const mrnReference = (req.body.mrnReference || '').trim()

    const isEndorse = !!req.body.endorse
    const isUpdate = !!req.body.update
    const isUpdateRefusal = !!req.body.updateRefusal

    delete data.errors
    delete data.errorList
    data.permit = permitId
    data.endorsedDetails = data.endorsedDetails || {}

    const errors = {}
    const errorList = []

    if (isUpdateRefusal) {
      const refusalReason = (req.body.refusalReason || '').trim()
      const additionalDetails = (req.body.additionalDetailsAmend || req.body.additionalDetailsAmendAlt || '').trim().slice(0, 200)
      if (!refusalReason) {
        errors.refusalReason = 'Select a reason for refusing this permit'
        errorList.push({ text: 'Select a reason for refusing this permit', href: '#refusalReason-error' })
      }
      if (errorList.length > 0) {
        data.errors = errors
        data.errorList = errorList
        return res.redirect(`${BASE}/single-search-results/check-permit-details?permit=${encodeURIComponent(permitId)}&edit=1#endorsement-section`)
      }
      const existing = data.endorsedDetails[permitId] || {}
      const port = currentPermit.port || 'Dover'
      const officerId = '233215'
      data.endorsedDetails[permitId] = {
        refusalReason,
        additionalDetails: additionalDetails || null,
        dateOfRefusal: existing.dateOfRefusal,
        port: existing.port || port,
        officerId: existing.officerId || officerId
      }
      delete data.editEndorsement
      return res.redirect(`${BASE}/single-search-results/check-permit-details?permit=${encodeURIComponent(permitId)}&updated=1`)
    }

    if (isEndorse || isUpdate) {
      if (!actualQuantity) {
        errors.actualQuantity = 'Enter the actual quantity'
        errorList.push({ text: 'Enter the actual quantity', href: '#actualQuantity' })
      } else if (!/^\d+$/.test(actualQuantity) || parseInt(actualQuantity, 10) < 1) {
        errors.actualQuantity = 'Actual quantity must be a whole number of 1 or more'
        errorList.push({ text: 'Actual quantity must be a whole number of 1 or more', href: '#actualQuantity' })
      }
      if (!mrnReference) {
        errors.mrnReference = 'Enter the customs document reference'
        errorList.push({ text: 'Enter the customs document reference', href: '#mrnReference' })
      }
    }

    if (errorList.length > 0) {
      data.endorsedDetails[permitId] = { actualQuantity, mrnReference }
      data.errors = errors
      data.errorList = errorList
      const editParam = isUpdate ? '&edit=1' : ''
      return res.redirect(`${BASE}/single-search-results/check-permit-details?permit=${encodeURIComponent(permitId)}${editParam}`)
    }

    delete data.errors
    delete data.errorList
    data.permitStatuses = data.permitStatuses || {}

    const port = currentPermit.port || 'Dover'
    const officerId = '233215'

    if (isUpdate) {
      const existing = data.endorsedDetails[permitId] || {}
      data.endorsedDetails[permitId] = {
        actualQuantity,
        mrnReference,
        dateOfEndorsement: existing.dateOfEndorsement,
        port: existing.port || port,
        officerId: existing.officerId || officerId
      }
      delete data.editEndorsement
      return res.redirect(`${BASE}/single-search-results/check-permit-details?permit=${encodeURIComponent(permitId)}&updated=1`)
    } else if (isEndorse) {
      const now = new Date()
      const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
      const day = now.getDate()
      const month = months[now.getMonth()]
      const year = now.getFullYear()
      const hours = String(now.getHours()).padStart(2, '0')
      const minutes = String(now.getMinutes()).padStart(2, '0')
      const dateOfEndorsement = `${day} ${month} ${year}, ${hours}:${minutes}`
      data.endorsedDetails[permitId] = { actualQuantity, mrnReference, dateOfEndorsement, port, officerId }
      data.permitStatuses[permitId] = 'endorsed'
      data.endorsed = true
      data.refused = false
      res.redirect(`${BASE}/single-search-results/check-permit-details?permit=${encodeURIComponent(permitId)}&endorsed=1`)
    } else {
      res.redirect(`${BASE}/single-search-results/check-permit-details?permit=${encodeURIComponent(permitId)}`)
    }
  })
}
